### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by NullVoxPopuli** [etkirsch/gmusic#22]
something ot handle this sort of thing when selecting a song / radio to play:

```
                                                                                                                       │
│                                      ↑↓: Nav     Space: ▶/||     n: Next     [ ]: Next/Prev Page     i: Cmd Line                                   Exception in thread Thread-1:                                                                                                                                       │
└────────────────────Traceback (most recent call last):─────────────────────────────────────────────────────────────────────────────────────────────────────┘
                                                         File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
                                                                                                                                   self.run()
                                                                                                                                               File "/usr/lib/python2.7/threading.py", line 763, in run
                                              self.__target(*self.__args, **self.__kwargs)
                                                                                            File "/home/preston/Development/gmusic/gmusic/frontend/UI.py", line 20, in __running__
                         self.get_user_input()
                                                File "/home/preston/Development/gmusic/gmusic/frontend/UI.py", line 34, in get_user_input
                                                                                                                                             self.ui_parser.parse(user_input)
                  File "/home/preston/Development/gmusic/gmusic/core/UIParser.py", line 8, in parse
                                                                                                       self.handler.handle(user_input)
                                                                                                                                        File "/home/preston/Development/gmusic/gmusic/core/UIHandler.py", line 16, in handle
                                                                   self.cmd_parser.parse(execution_command)
                                                                                                             File "/home/preston/Development/gmusic/gmusic/core/CommandParser.py", line 19, in parse
                                           self.handle(data)
                                                              File "/home/preston/Development/gmusic/gmusic/core/CommandParser.py", line 26, in handle
                                                                                                                                                          method(data[1])
              File "/home/preston/Development/gmusic/gmusic/core/CommandHandler.py", line 33, in typed_play
                                                                                                               self.player_controller.play_radio(args[1])
                                                                                                                                                           File "/home/preston/Development/gmusic/gmusic/player/PlayerController.py", line 23, in play_radio
                                                                                                   tracks = self.content_handler.client.get_radio_contents(rid)
    File "/home/preston/Development/gmusic/gmusic/content/GMusicClient.py", line 21, in get_radio_contents
                                                                                                              tracks = self.client.get_station_tracks(radio_id)
    File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 787, in get_station_tracks
                                                                                                                        station_id, num_tracks, recently_played=recently_played)
                     File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/shared.py", line 80, in _make_call
                                                                                                                          return protocol.perform(self.session, self.validate, *args, **kwargs)
                                    File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 208, in perform
                                                                                                                                        response = session.send(req_kwargs, cls.required_auth)
                                   File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 86, in send
                                                                                                                           res = self._send_with_auth(req_kwargs, desired_auth, rsession)
                              File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 195, in _send_with_auth
                                                                                                                                  return rsession.request(**req_kwargs)
            File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
                                                                                                  resp = self.send(prep, **send_kwargs)
                                                                                                                                         File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
                                                               r = adapter.send(request, **kwargs)
                                                                                                    File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
                          raise ConnectionError(err, request=request)
                                                                     ConnectionError: ('Connection aborted.', gaierror(-3, 'Temporary failure in name resolution'))

      preston@preston-VirtualBox 10.10.12.42  ~/Development/gmusic
💎  2.2.3 (master) $ 

```

**Comment by NullVoxPopuli** [comment]
Looks like the same error, but from a slightly different cause:

```
./run
Traceback (most recent call last):
  File "gmusic.py", line 4, in <module>
    gm.start()
  File "/home/preston/Development/gmusic/gmusic/core/Core.py", line 33, in start
    cmd_parser, ui_parser = self.build_parsers()
  File "/home/preston/Development/gmusic/gmusic/core/Core.py", line 20, in build_parsers
    content_handler.launch()
  File "/home/preston/Development/gmusic/gmusic/content/ContentHandler.py", line 11, in launch
    self.client.login()
  File "/home/preston/Development/gmusic/gmusic/content/GMusicClient.py", line 13, in login
    self.client.login(credentials['username'], credentials['password'], mac)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 64, in login
    if not self.session.login(email, password, android_id):
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 170, in login
    res = gpsoauth.perform_master_login(email, password, android_id)
  File "/usr/local/lib/python2.7/dist-packages/gpsoauth/__init__.py", line 66, in perform_master_login
    return _perform_auth_request(data)
  File "/usr/local/lib/python2.7/dist-packages/gpsoauth/__init__.py", line 22, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-3, 'Temporary failure in name resolution'))
```

**Comment by etkirsch** [comment]
Lack of error handling confirmed. Will add.

**Comment by NullVoxPopuli** [comment]
Implementation idea:

-> Log exceptions to a log file and have that thread proceed if it can
   -> only if a particular thread cannot be recovered from, should the program crash
      -> if this happens, there should be an additional file made that a user can copy and paste information to in order to report the issue here an github
-> Have another thread watch the log file and notify the user when an exception has been logged

**Comment by etkirsch** [comment]
In startup.py, have a try/catch, then log it to the file and clean up the output ('tty sane')
