### ISSUE TITLE
local variable url referenced before assignment

### ISSUE THREAD

**Issue by NullVoxPopuli** [etkirsch/gmusic#29]
```
   별이 뜬다 Stars Appear...                                                               
                                                              DEVIL - SUPER JUNIOR SPECIAL ALBUM                                                            │
│                                                                        SUPER JUNIOR                                                                      Exception in thread Thread-1:                                                                                                                                 │
│ Radios (Page 12 of 12)   Traceback (most recent call last):                                                                                               │
│                                                              File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner                       │
│ Options                                                                                                                                self.run()         │
│   1.                                                                                                                                               File "/usr/lib/python2.7/threading.py", line 763, in run                                                                                                            │
│   3.  Me And You                                  self.__target(*self.__args, **self.__kwargs)                                                            │
│   4.  Between Two Points (Comma Remix).mp3                                                      File "/home/preston/Development/gmusic/gmusic/frontend/UI.py", line 20, in __running__                                                                                                                                 │
│   6.  Sun & Moon             self.get_user_input()                                                                                                        │
│   7.  The Plan                                      File "/home/preston/Development/gmusic/gmusic/frontend/UI.py", line 34, in get_user_input             │
│   8.  Invasion - ASOT 550 Anthem (Original Mix)                                                                                                  self.ui_parser.parse(user_input)                                                                                                                                      │
│   10. Back            File "/home/preston/Development/gmusic/gmusic/core/UIParser.py", line 8, in parse                                                   │
│                                                                                                            self.handler.handle(user_input)                │
│                                                                                                                                             File "/home/preston/Development/gmusic/gmusic/core/UIHandler.py", line 16, in handle                                                                                       │
│                                                                        self.cmd_parser.parse(execution_command)                                           │
│                                                                                                                  File "/home/preston/Development/gmusic/gmusic/core/CommandParser.py", line 19, in parse                                                                                                               │
│                                                self.handle(data)                                                                                          │
│                                                                   File "/home/preston/Development/gmusic/gmusic/core/CommandParser.py", line 26, in handle│
│                                                                                                                                                               method(data[1])                                                                                                                                          │
│                   File "/home/preston/Development/gmusic/gmusic/core/CommandHandler.py", line 33, in typed_play                                           │
│                                                                                                                    self.player_controller.play_radio(args[1])                                                                                                                                                          │
│   File "/home/preston/Development/gmusic/gmusic/player/PlayerController.py", line 26, in play_radio                                                       │
│                                                                                                        self.play(nids[0])                                 │
│                                                                                                                            File "/home/preston/Development/gmusic/gmusic/player/PlayerController.py", line 50, in play                                                                                                 │
│                                                              self.player.play(url)                                                                        │
│                                                                                   UnboundLocalError: local variable 'url' referenced before assignment    │
│                                                                                                                                                           │
```

I selected L.OV.E. Girl radio 
The first song it tried to play was by Super Junior

:-\

**Comment by etkirsch** [comment]
fixed in `exterminator`

**Comment by NullVoxPopuli** [comment]
looks good!
