### ISSUE TITLE
Invalid request when seeding a radio with a song

### ISSUE THREAD

**Issue by NullVoxPopuli** [etkirsch/gmusic#33]
```
exception in thread Thread-1:                                                                                                                                 │
│ Main Menu                Traceback (most recent call last):                                                                                               │
│                                                              File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner                       │
│ Options                                                                                                                                self.run()         │
│   1.  Artists                                                                                                                                      File "/usr/lib/python2.7/threading.py", line 763, in run                                                                                                            │
│   3.  Radios                                      self.__target(*self.__args, **self.__kwargs)                                                            │
│   4.  Songs                                                                                     File "/home/preston/Development/gmusic/gmusic/frontend/UI.py", line 20, in __running__                                                                                                                                 │
│   6.  Options                self.get_user_input()                                                                                                        │
│   7.  Exit                                          File "/home/preston/Development/gmusic/gmusic/frontend/UI.py", line 35, in get_user_input             │
│                                                                                                                                                  self.ui_parser.parse(user_input)                                                                                                                                      │
│                       File "/home/preston/Development/gmusic/gmusic/core/UIParser.py", line 8, in parse                                                   │
│                                                                                                            self.handler.handle(user_input)                │
│                                                                                                                                             File "/home/preston/Development/gmusic/gmusic/core/UIHandler.py", line 34, in handle                                                                                       │
│                                                                        self.cmd_parser.parse(cmd)                                                         │
│                                                                                                    File "/home/preston/Development/gmusic/gmusic/core/CommandParser.py", line 19, in parse                                                                                                                             │
│                                  self.handle(data)                                                                                                        │
│                                                     File "/home/preston/Development/gmusic/gmusic/core/CommandParser.py", line 26, in handle              │
│                                                                                                                                                 method(data[1])                                                                                                                                                        │
│     File "/home/preston/Development/gmusic/gmusic/core/CommandHandler.py", line 23, in typed_seed                                                         │
│                                                                                                      radio_id = self.content_handler.create_radio(seed_type, id, name)                                                                                                                                                 │
│            File "/home/preston/Development/gmusic/gmusic/content/ContentHandler.py", line 30, in create_radio                                             │
│                                                                                                                  radio_id = self.client.create_radio(seed_type, id, name)                                                                                                                                              │
│               File "/home/preston/Development/gmusic/gmusic/content/GMusicClient.py", line 51, in create_radio                                            │
│                                                                                                                   return self.client.create_station(name=name, track_id=ids['track'], album_id=ids['album'], artist_id=ids['artist'])                                                                                  │
│                                                                           File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 706, in create_station                                                                                                                                 │
│                              res = self._make_call(mutate_call, [add_mutation])                                                                           │
│                                                                                  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/shared.py", line 80, in _make_call                                                                                                                                     │
│                          return protocol.perform(self.session, self.validate, *args, **kwargs)                                                            │
│                                                                                                 File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 246, in perform                                                                                                                       │
│                                        cls.check_success(response, parsed_response)                                                                       │
│                                                                                      File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/mobileclient.py", line 415, in check_success                                                                                                                      │
│                                         cls.__name__)                                                                                                     │
│                                                      CallFailure: BatchMutateStations: The server reported failure while changing the requested resource. If this wasn't caused by invalid arguments or server flakiness, please open an issue.                                                                        │
│                                                                                   (requests kwargs: {'url': 'https://mclients.googleapis.com/sj/v1.11/radio/editstation', 'headers': {'Content-Type': 'application/json', 'Authorization': '<omitted>'}, 'data': '{"mutations": [{"createOrGet": {"tracks": [], "seed": {}, "imageType": 1, "deleted": false, "lastModifiedTimestamp": "-1", "recentTimestamp": "1449493528316015", "clientId": "30199cf8-9ce3-11e5-bb1b-0800275da88a", "name": "Phantazmz"}, "includeFeed": false, "params": {"contentFilter": 1}, "numEntries": 0}]}', 'method': 'POST', 'params': {'alt': 'json'}})           │
│                                                                                                                                                (response was: '{\n "mutate_response": [\n  {\n   "id": "",\n   "response_code": "INVALID_REQUEST"\n  }\n ]\n}\n')  
```

**Comment by etkirsch** [comment]
Fixed?

**Comment by NullVoxPopuli** [comment]
yup!
