### ISSUE TITLE
invalid commands not handled

### ISSUE THREAD

**Issue by NullVoxPopuli** [etkirsch/gmusic#56]
tried:
` exit` aka {space}exit
`spacexit`
`yolo`
```
p           │
│        ↔ : Change Page       q : Play NeTraceback (most recent call last):        │
│                              i : CLI         Space : ▶/❚❚                   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner                     │
└──────────────────────────────────────────────────────────────    self.run()───────
                                                                               File "/usr/lib/python2.7/threading.py", line 763, in run
                                                      self.__target(*self.__args, **self.__kwargs)
               File "/home/preston/Development/gmusic/gmusic/frontend/UI.py", line 23, in __running__
                    self.get_user_input()
                                           File "/home/preston/Development/gmusic/gmusic/frontend/UI.py", line 33, in get_user_input
                                                   result = self.handle_text_entry()
                                                                                      File "/home/preston/Development/gmusic/gmusic/frontend/UI.py", line 55, in handle_text_entry
            self.cmd_processor.parse(request)
                                               File "/home/preston/Development/gmusic/gmusic/core/CommandProcessor.py", line 41, in parse
                                                        self.process(cmd_class.capitalize(), cmd_args)
                   File "/home/preston/Development/gmusic/gmusic/core/CommandProcessor.py", line 16, in process
                              command.player_controller = self.player_controller
                                                                                AttributeError: 'NoneType' object has no attribute 'player_controller'

```

**Comment by etkirsch** [comment]
fixed
