### ISSUE TITLE
startup script crashes

### ISSUE THREAD

**Issue by NullVoxPopuli** [etkirsch/gmusic#59]
immediately after hitting enter after typing in my password.
looks like you need to create the directories if they don't exist.
```
Traceback (most recent call last):
  File "startup.py", line 12, in <module>
    with open('data/unlocked/credentials.json','w') as credentials:
IOError: [Errno 2] No such file or directory: 'data/unlocked/credentials.json'
Traceback (most recent call last):
  File "gmusic.py", line 1, in <module>
    from gmusic.core.Core import Core
  File "/home/lprestonsegoiii/Development/gmusic/gmusic/__init__.py", line 4, in <module>
    from gmusic.core import *
  File "/home/lprestonsegoiii/Development/gmusic/gmusic/core/__init__.py", line 3, in <module>
    from gmusic.core.Core import Core
  File "/home/lprestonsegoiii/Development/gmusic/gmusic/core/Core.py", line 1, in <module>
    from gmusic.content.ContentHandler import ContentHandler
  File "/home/lprestonsegoiii/Development/gmusic/gmusic/content/__init__.py", line 2, in <module>
    from gmusic.content.ContentHandler import ContentHandler
  File "/home/lprestonsegoiii/Development/gmusic/gmusic/content/ContentHandler.py", line 3, in <module>
    from gmusic.content.GMusicClient import GMusicClient
  File "/home/lprestonsegoiii/Development/gmusic/gmusic/content/GMusicClient.py", line 2, in <module>
    from gmusicapi import Mobileclient
ImportError: No module named gmusicapi
```

**Comment by etkirsch** [comment]
closed with 5663a1e I believe
