### ISSUE TITLE
Startup script crashes, AttributeError

### ISSUE THREAD

**Issue by NullVoxPopuli** [etkirsch/gmusic#64]
possibly relates to #61 

```
$ ./run
Traceback (most recent call last):
  File "startup.py", line 1, in <module>
    from gmusic.core.Core import Core
  File "/home/me/OpenSource/gmusic/gmusic/__init__.py", line 4, in <module>
    from gmusic.core import *
AttributeError: 'module' object has no attribute 'Cache'
```

**Comment by NullVoxPopuli** [comment]
i do, though it should tell me if I don't have credentials

**Comment by etkirsch** [comment]
Reproduced. Looking into it

**Comment by etkirsch** [comment]
okay I have fixed that issue and am working on making the startup work now

**Comment by NullVoxPopuli** [comment]
woo
